deps: include grpc dependencies
googleapis/java-spanner-jdbc pull request #278
Opened 2020-11-19 19:56 UTC by olavloite

Adds the `grpc-google-cloud-spanner-...` dependencies as compile time dependencies.

Fixes the failure in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/4278

2020-11-19 20:04 UTC, elharo requested changes
I don't think this is correct. If they're not needed by this project's compile classpath, they should be added in the downstream project; not here.

2020-11-20 09:54 UTC, olavloite commented
> I don't think this is correct. If they're not needed by this project's compile classpath, they should be added in the downstream project; not here.

@elharo 
Hmmm... That is true. It should however be a compile time dependency that should be included automatically as a transitive dependency from `google-cloud-spanner`. So I agree, adding it here is not the real solution.

It seems that there are a couple of problems here:
1. The reason that the `grpc-google-cloud-spanner-admin-...` dependencies were not considered transitive, was that they were added explicitly as test dependencies. Removing those as test dependencies is enough to solve this specific problem.
1. All other compile time dependencies currently declared in the JDBC pom can now also be removed, except for the dependency on `google-cloud-spanner`.
1. The JDBC pom imports a specific version of `google-cloud-spanner-bom`, which determines the version of the Spanner client library to use. The version that is specified there is not transitive. That means that any application that imports the `libraries-bom` and adds `google-cloud-spanner-jdbc` as a dependency will get the versions of `google-cloud-spanner` and `google-cloud-spanner-jdbc` that are defined in `libraries-bom`. The version of `google-cloud-spanner` in `libraries-bom` can be different from the one defined in `google-cloud-spanner-jdbc`. This is currently also the case, as `google-cloud-spanner-jdbc` imports version 2.0.2, while the `libraries-bom` specifies version 3.0.4. The latter version will be added as a compile time dependency for an application that defines `google-cloud-spanner-jdbc` as a dependency.

@suztomo Any ideas what the best approach would be for the third point?

2020-11-20 10:07 UTC, olavloite commented on pom.xml
>        <artifactId>google-cloud-spanner</artifactId>
The version that is used here will be determined by the version defined at line 72 for the import of `google-cloud-spanner-bom` (currently 2.0.2). That is the version of `google-cloud-spanner` that anyone using `google-cloud-spanner-jdbc` should be using. But:
* Any application that adds only `google-cloud-spanner-jdbc` (version 1.17.3) as a dependency without importing the `libraries-bom` will get `google-cloud-spanner` version 2.0.2.
* Any application that adds `google-cloud-spanner-jdbc` as a dependency and imports the `libraries-bom`, will get the versions of `google-cloud-spanner-jdbc` and `google-cloud-spanner` that are defined in the `libraries-bom`. The version of `google-cloud-spanner` in the BOM can be different from the one defined in `google-cloud-spanner-jdbc`.

2020-11-23 14:22 UTC, suztomo commented
I agree with Elliotte's point. If some artifacts are missing proper dependencies, we should fix that there.

Let me dig your finding further. https://github.com/GoogleCloudPlatform/java-docs-samples/pull/4278#issuecomment-730598685

2020-11-23 17:45 UTC, olavloite commented
> I agree with Elliotte's point. If some artifacts are missing proper dependencies, we should fix that there.
> 

Yes, I agree with that. But in this case it should be a transitive dependency, but seems to have lost that status. And that seems to be caused by the fact that it was added as a test dependency in the pom of this project, while it was already a compile-time dependency. I have not been able to find a satisfactory explanation as to why the dependency was still transitive in earlier versions of the JDBC driver, but not anymore.

2020-11-24 18:14 UTC, elharo approved these changes
I'm a little surprised Maven doesn't flag this issue (declaring the same dependency in multiple scopes) as an error.

2020-11-24 19:18 UTC, merged